CREATE DATABASE RECLAMOS_2022;
USE RECLAMOS_2022;

CREATE TABLE Sector (
    ID_SECTOR INT PRIMARY KEY,
    Sector VARCHAR(255)
);

CREATE TABLE MedioIngreso (
    ID_TIPO_DE_INGRESO VARCHAR(255) PRIMARY KEY,
    Tipo_de_ingreso VARCHAR(255)
);

CREATE TABLE MedioPago (
    ID_MODALIDAD_DE_PAGO VARCHAR(255) PRIMARY KEY,
    Modalidad_de_pago VARCHAR(255)
);

CREATE TABLE ClasificacionBien (
    ID_CLASIFICACION INT PRIMARY KEY,
    Descripcion VARCHAR(255)
);

CREATE TABLE ClasificacionProblemasEspeciales (
    ID_TIPO_PROBLEMA VARCHAR(255) PRIMARY KEY,
    Problema_especial VARCHAR(255)
);

CREATE TABLE TipoConciliacion (
    ID_TIPO_CONCILIACION INT PRIMARY KEY,
    Tipo_de_conciliacion VARCHAR(255)
);

CREATE TABLE TipoEstadoProcesal (
    ID_TIPO_ESTADO_PROCESAL INT PRIMARY KEY,
    Estado_Procesal VARCHAR(255)
);

CREATE TABLE TipoReclamo (
    ID_TIPO_DE_RECLAMO VARCHAR(255) PRIMARY KEY,
    Tipo_de_reclamo VARCHAR(255)
);

CREATE TABLE Procedimiento (
    ID_TIPO_PROCEDIMIENTO VARCHAR(255) PRIMARY KEY,
    Procedimiento VARCHAR(255)
);

CREATE TABLE MotivoReclamo (
    ID INT PRIMARY KEY,
    Descripcion VARCHAR(255)
);

CREATE TABLE TipoProducto (
    ID_TIPO_DE_PRODUCTO INT PRIMARY KEY,
    Tipo_de_producto VARCHAR(255),
    ID_CLASIFICACION INT,
    FOREIGN KEY (ID_CLASIFICACION) REFERENCES ClasificacionBien(ID_CLASIFICACION)
);

CREATE TABLE ModalidadCompra (
    ID_MODALIDAD_COMPRA VARCHAR(255) PRIMARY KEY,
    Modalidad_de_compra VARCHAR(255),
    ID_TIPO_DE_INGRESO VARCHAR(255),
    ID_MODALIDAD_DE_PAGO VARCHAR(255),
    FOREIGN KEY (ID_TIPO_DE_INGRESO) REFERENCES MedioIngreso(ID_TIPO_DE_INGRESO),
    FOREIGN KEY (ID_MODALIDAD_DE_PAGO) REFERENCES MedioPago(ID_MODALIDAD_DE_PAGO)
);

CREATE TABLE Proveedor (
    ID_PROVEEDOR INT PRIMARY KEY,
    Proveedor VARCHAR(255),
    ID_SECTOR INT,
    FOREIGN KEY (ID_SECTOR) REFERENCES Sector(ID_SECTOR)
);

CREATE TABLE Reclamos (
    ID_EXP INT PRIMARY KEY,
    FECHA_INGRESO DATE,
    FECHA_FIN DATE,
    FECHA_DE_CIERRE DATE,
    COSTO_BIEN_SERVICIO DECIMAL(18,2),
    MONTO_RECLAMADO DECIMAL(18,2),
    MONTO_RECUPERADO DECIMAL(18,2),
    ID_TIPO_CONCILIACION INT,
    ID_TIPO_ESTADO_PROCESAL INT,
    ID_PROVEEDOR INT,
    ID_TIPO_DE_RECLAMO VARCHAR(255),
    ID_MOTIVO INT,
    ID_PROCEDIMIENTO VARCHAR(255),
    ID_TIPO_DE_PRODUCTO INT,
    ID_TIPO_DE_COMPRA VARCHAR(255),
    ID_PROBLEMA_ESPECIAL VARCHAR(255),
    FOREIGN KEY (ID_TIPO_CONCILIACION) REFERENCES TipoConciliacion(ID_TIPO_CONCILIACION),
    FOREIGN KEY (ID_TIPO_ESTADO_PROCESAL) REFERENCES TipoEstadoProcesal(ID_TIPO_ESTADO_PROCESAL),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES Proveedor(ID_PROVEEDOR),
    FOREIGN KEY (ID_TIPO_DE_RECLAMO) REFERENCES TipoReclamo(ID_TIPO_DE_RECLAMO),
    FOREIGN KEY (ID_MOTIVO) REFERENCES MotivoReclamo(ID),
    FOREIGN KEY (ID_PROCEDIMIENTO) REFERENCES Procedimiento(ID_TIPO_PROCEDIMIENTO),
    FOREIGN KEY (ID_TIPO_DE_PRODUCTO) REFERENCES TipoProducto(ID_TIPO_DE_PRODUCTO),
    FOREIGN KEY (ID_TIPO_DE_COMPRA) REFERENCES ModalidadCompra(ID_MODALIDAD_COMPRA),
    FOREIGN KEY (ID_PROBLEMA_ESPECIAL) REFERENCES ClasificacionProblemasEspeciales(ID_TIPO_PROBLEMA)
);